### ISSUE TITLE
[feature request] --dry-run option

### ISSUE THREAD

**Issue by raquelxmoss** [not-an-aardvark/git-delete-squashed#9]
Hi! Thanks for this 😄. I would love to see a `--dry-run`  option so that I can see what will be deleted before going ahead. Would that be feasible?

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue.

I'd like to keep the script in this repo configuration-free to make it as easy as possible to use, so I don't think I want to add command-line flags. However, if you want dry-run functionality it would probably be relatively simple to create by modifying the script (e.g. by changing the part at the end that runs `git branch -D $branch` to run something like `echo "$branch is ready to be deleted"` instead).

Closing this issue since I don't think I want to change this, but feel free to continue the conversation if you have any questions about how one might implement this as a fork/modification.

**Comment by raquelxmoss** [comment]
Hey @not-an-aardvark, thanks for the guidance. When I have some time I'll fork this and give it a go. Cheers!

**Comment by raquelxmoss** [comment]
I made a fork and just added a really quick-and-dirty version. Here's the link in case anyone has the same feature request: https://github.com/raquelxmoss/git-delete-squashed.

Cheers! 🍻

**Comment by solarmosaic-kflorence** [comment]
Thanks @raquelxmoss -- I, too, like to see what is going to be deleted before deleting it. For others who stumble here, you can add this as a git alias to your `.gitconfig` which allows you to optionally pass the `--dry-run` parameter:

```
[alias]
    delete-squashed = !git-delete-squashed $@
```
